spring:
  application:
    name: url-shortening-service
  datasource:
    url: jdbc:h2:mem:urlshortener
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: top-shortened-domains