spring:
  application:
    name: url-shortening-service

server:
  error:
    include-message: always

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: top-shortened-domains